front 개발 환경 설정
boostcamp-2020/IssueTracker-35 pull request #3
Opened 2020-10-27 13:23 UTC by kyu9341

# 개요
- webpack, babel 설정
  - 배포용, 개발용으로 분리하여 설정
  - `webpack-merge`를 사용하여 공통적인 부분은 `webpack.common.js`에 넣음
- eslint, prettier 설정

# 체크리스트
- [x] `npm run dev` 로 빌드 시 개발용 웹팩 설정으로 빌드
- [x] `npm run build`로 빌드 시 배포용 웹팩 설정으로 빌드
- [x] 빌드 시 오류 발생하는지

2020-10-27 13:30 UTC, pjy0416 requested changes
.gitignore에 .env 제외하는 부분에 오타가 있습니다 !!

2020-10-27 13:30 UTC, pjy0416 commented on .gitignore
> -.env
.gitignore에 .env 오타가 있는 것 같아요 !!

2020-10-27 13:43 UTC, kyu9341 commented on .gitignore
> -.env
앗.. 수정했습니다!!

2020-10-28 00:52 UTC, joh16 approved these changes
개발 환경 설정이 이렇게 어려울줄은 몰랐지만... 이제 예쁘게 개발할 수 있겠네요!

2020-10-28 00:55 UTC, limaries30 approved these changes
좋아요!

2020-10-28 01:01 UTC, pjy0416 approved these changes
감사합니다!

2020-10-28 01:01 UTC, merged