이슈 생성 API 테스트 코드 작성
boostcamp-2020/IssueTracker-35 pull request #59
Opened 2020-11-10 05:48 UTC by pjy0416

- 개요
   - 이슈 생성 API를 위한 테스트 코드
   - service (issue, assignment, issue-label, comment)
   - api (issue-api)
- 체크리스트
   - service 성공 코드 작성
   - api test에서 bad request 상황이 잘 작성됨

2020-11-10 08:04 UTC, joh16 commented on server/test/api/issue.api.test.js
> +    }; // userID는 아래 토큰 생성 과정에서 담긴다
token parsing 과정인데, 굳이 comment로 적지 않아도 될 것 같습니다

2020-11-10 08:07 UTC, kyu9341 approved these changes
테스트코드도 양이 많군요..! 고생하셨습니다!!

2020-11-10 08:13 UTC, pjy0416 commented on server/test/api/issue.api.test.js
> +    }; // userID는 아래 토큰 생성 과정에서 담긴다
수정했습니다!

2020-11-10 08:13 UTC, pjy0416 commented
> 테스트코드도 양이 많군요..! 고생하셨습니다!!

TDD 조아..

2020-11-10 08:33 UTC, kyu9341 requested changes

2020-11-10 08:33 UTC, kyu9341 commented on server/main/controllers/issue.js
> +        labels.forEach(labelID => issueLabelService.create(issueID, labelID)),
이 부분에서 create를 여러 번 호출하는 것보다 bulkCreate로 한 번에 넣는게 더 좋지 않을까요!?

2020-11-10 08:33 UTC, kyu9341 commented on server/main/controllers/issue.js
> +      return next(err);
모든 상황에서 같은 동작을 한다면 else if 대신 전부 if 문으로 작성해도 되지않을까요?

2020-11-10 08:44 UTC, joh16 commented on server/main/controllers/issue.js
> +      let milestoneID = null;
milestoneID = milestone[0]을 바로 때려도 비어 있으면 undefined로 들어가긴 합니다.

null이든 undefined든 sequelize가 똑같이 (SQL)null 처리해주는걸로 알고있습니다.

2020-11-10 08:45 UTC, joh16 commented on server/main/controllers/issue.js
> +        content = null;
이것도 아마 알아서 undefined가 되어있을 것입니다...

2020-11-10 08:46 UTC, joh16 commented on server/main/controllers/issue.js
> +        parseInt(milestoneID)
(없어도 될 것 같은데 그 와중에 userID는 안 감싸셨...)

2020-11-10 08:48 UTC, joh16 commented on server/main/controllers/issue.js
> +      await Promise.all([
transaction으로 묶어서 처리해주면 하다가 DB가 미국을 가도 롤백이 가능할 듯 합니다.

2020-11-10 08:53 UTC, joh16 commented on server/main/controllers/issue.js
> +    if (typeof title !== 'string' || title === '') {
```jsx
switch (true) {
  case (invalid_condition1): // fallthrough
  case (invalid_condition2): // fallthrough
  ...
    return next(err);
  default:
    return next();
```

같은 문법도 있으니 참고하셔도 좋을 것 같습니다. 물론 꼭 고쳐야 하는건 아니에요!

2020-11-10 08:55 UTC, joh16 commented on server/main/controllers/issue.js
> +          result = false;
FYI: 바로 return false 해도 될것 같습니다

2020-11-10 08:56 UTC, pjy0416 commented on server/main/controllers/issue.js
> +        labels.forEach(labelID => issueLabelService.create(issueID, labelID)),
여러번 쿼리를 날리는 것 보다는 forEach로 data를 생성해서 bulk query로 처리하는게 더 효율적이겠네요.
반영했습니다!!

2020-11-10 08:57 UTC, joh16 commented on server/main/controllers/issue.js
> +          assignmentService.create(issueID, assignee)
이러면 query가 여러 번 날아갈 것 같은데, bulk create으로 바꿀 수 있지 않을까요?

2020-11-10 08:58 UTC, pjy0416 commented on server/main/controllers/issue.js
> +      return next(err);
위의 사항은 else if나 if나 같은 상황이네요..
if가 더 적절한 것 같습니다!
수정했습니다!

2020-11-10 09:00 UTC, pjy0416 commented on server/main/controllers/issue.js
> +      let milestoneID = null;
sequelize에서 자체적으로 null로 변환을 해주는군요.. 조금 더 찾아보고 진행했어야하는데, 감사합니다!!

2020-11-10 09:01 UTC, joh16 commented on server/main/controllers/issue.js
> +      let milestoneID = null;
(아 근데 milestone이 undefined면 [0]했을 때 죽긴 합니다)

2020-11-10 09:02 UTC, pjy0416 commented on server/main/controllers/issue.js
> +        parseInt(milestoneID)
이 부분도 알아서 변환을 해주는군요..
userID는 number 형태로 저장되어 있습니다 !!
null을 parsing 할 수 있는 상황에 동감해서, 반영했습니다!

2020-11-10 09:03 UTC, pjy0416 commented on server/main/controllers/issue.js
> +    if (typeof title !== 'string' || title === '') {
swich case보다 if문을 선호하는... ㅎㅎㅎ
case 자체가 방대하지 않아서 if도 괜찮다고 판단했습니다!!
혹시나 check할 사항이 더 많아진다면, 꼭 반영하겠습니다

2020-11-10 09:05 UTC, joh16 requested changes
bulk create이랑 transaction은 적용하는 것이 좋은 백엔드 개발자가 되는 밑거 름이 될 것입니다.

2020-11-10 09:05 UTC, pjy0416 commented on server/main/controllers/issue.js
> +          result = false;
자바스크립트 forEach 구문에서는 바로 return이나 break가 안되는 것으로 알고있습니다 !!
이 전에 코드가 forEach 안쪽에서 return해주는 코드였는데, false인 상황을 못걸렀습니다.. ㅠㅠ

2020-11-10 09:07 UTC, pjy0416 reviewed
> bulk create이랑 transaction은 적용하는 것이 좋은 백엔드 개발자가 되는 밑거 름이 될 것입니다.

밑거 ~~믿거~~ 인가요 .. ㅎㅎ transaction 적용하겠습니다

2020-11-10 13:05 UTC, kyu9341 approved these changes

2020-11-10 16:03 UTC, pjy0416 commented on server/main/controllers/issue.js
> +      await Promise.all([
미국보냈다가 송환처리 했습니다

2020-11-11 01:13 UTC, kyu9341 commented
진짜 고생 많으셨습니다~ 
TDD와 전투의 흔적..

2020-11-11 01:15 UTC, joh16 commented on server/main/controllers/issue.js
> +          result = false;
그러면 `return array.find(value => typeof value !== 'string') === -1`로 해도 되겠네요

2020-11-11 01:23 UTC, pjy0416 commented on server/main/controllers/issue.js
> +          result = false;
some으로 바꿨습니다!

2020-11-11 01:34 UTC, joh16 approved these changes
transaction까지 적용하셨군요! 멋집니다~

2020-11-11 01:34 UTC, merged